import os
import asyncio
from telegram import Bot
import google.generativeai as genai
import aiohttp
from bs4 import BeautifulSoup

BOT_TOKEN = os.environ.get("BOT_TOKEN")
CHANNEL_ID = "@nabz_bollywood"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

print(f"BOT_TOKEN exists: {bool(BOT_TOKEN)}")
print(f"GEMINI_API_KEY exists: {bool(GEMINI_API_KEY)}")

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

async def translate_news(text):
    try:
            prompt = f"""این خبر بالیوودی رو به فارسی روان و جذاب ترجمه کن.
            اسم فیلم‌ها: فارسی (انگلیسی)
            در آخر هشتگ اضافه کن.
            فرمت:
            🎬 عنوان

            متن خبر

            #بالیوود #Bollywood #سینمای_هند

            خبر: {text}"""
                    response = model.generate_content(prompt)
                            print(f"Gemini response OK")
                                    return response.text
                                        except Exception as e:
                                                print(f"Gemini error: {e}")
                                                        return None

                                                        async def get_news():
                                                            news = []
                                                                headers = {"User-Agent": "Mozilla/5.0"}
                                                                    async with aiohttp.ClientSession() as session:
                                                                            try:
                                                                                        url = "https://www.bollywoodhungama.com/rss/news.xml"
                                                                                                    async with session.get(url, headers=headers, timeout=15) as r:
                                                                                                                    print(f"BH status: {r.status}")
                                                                                                                                    if r.status == 200:
                                                                                                                                                        soup = BeautifulSoup(await r.text(), 'xml')
                                                                                                                                                                            items = soup.find_all('item')
                                                                                                                                                                                                print(f"BH items found: {len(items)}")
                                                                                                                                                                                                                    for item in items[:3]:
                                                                                                                                                                                                                                            t = item.find('title')
                                                                                                                                                                                                                                                                    d = item.find('description')
                                                                                                                                                                                                                                                                                            if t and d:
                                                                                                                                                                                                                                                                                                                        news.append({"title": t.text.strip(), "desc": d.text.strip()[:400]})
                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                            print(f"BH error: {e}")

                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                url = "https://www.filmfare.com/rss/news.xml"
                                                                                                                                                                                                                                                                                                                                                                            async with session.get(url, headers=headers, timeout=15) as r:
                                                                                                                                                                                                                                                                                                                                                                                            print(f"FF status: {r.status}")
                                                                                                                                                                                                                                                                                                                                                                                                            if r.status == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                soup = BeautifulSoup(await r.text(), 'xml')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    items = soup.find_all('item')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"FF items found: {len(items)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for item in items[:3]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    t = item.find('title')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            d = item.find('description')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if t and d:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                news.append({"title": t.text.strip(), "desc": d.text.strip()[:400]})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"FF error: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Total news: {len(news)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return news

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Starting bot...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bot = Bot(token=BOT_TOKEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Test bot connection
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        me = await bot.get_me()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Bot connected: @{me.username}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Bot connection error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Test channel access
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    chat = await bot.get_chat(CHANNEL_ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Channel found: {chat.title}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Channel error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    news = await get_news()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not news:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("No news found!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Send test message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await bot.send_message(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                chat_id=CHANNEL_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text="🎬 تست نبض بالیوود\n\nربات آنلاینه و داره کار میکنه!\n\n#بالیوود #Bollywood"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Test message sent!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Test message error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for item in news[:2]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raw = f"{item['title']}\n\n{item['desc']}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        formatted = await translate_news(raw)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not formatted:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await bot.send_message(chat_id=CHANNEL_ID, text=formatted[:4096])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Sent: {item['title'][:50]}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await asyncio.sleep(3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Send error: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                asyncio.run(main())
